version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  loyalty_service:
    container_name: loyalty_service
    build:
      context: src
      dockerfile: Booking.System/Booking.System.LoyaltyService/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8050:8050"
  
  payment_service:
    container_name: payment_service
    build:
      context: src
      dockerfile: Booking.System/Booking.System.PaymentService/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8060:8060"
  
  reservation_service:
    container_name: reservation_service
    build:
      context: src
      dockerfile: Booking.System/Booking.System.ReservationService/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8070:8070"
  
  gateway_service:
    container_name: gateway_service
    build:
      context: src
      dockerfile: Booking.System/Booking.System.Gateway/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  db-data: